### ISSUE TITLE
Timeout support

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cmd#10]
In getting feedback, there came up the need for timeout support.

We'd have to run the command in a thread, sleep for the time (in small increments?), and then call kill if needed.

https://doc.rust-lang.org/std/process/struct.Child.html#method.kill

**Comment by epage** [comment]
See discussion at https://github.com/assert-rs/assert_cli/issues/67

**Comment by epage** [comment]
From [previous thread](https://github.com/assert-rs/assert_cli/issues/67)

Looks like this will be pretty trivial
https://crates.io/crates/wait-timeout

Nevermind, it doesn't support getting the output and it doesn't look like it will in the foreseeable future
https://github.com/alexcrichton/wait-timeout/pull/4

**Comment by vincentdephily** [comment]
For my use, I'm simply looping through all my currently-live commands and calling thread::sleep(10ms) before looping again. Not pretty but it works. I've found 10ms to be useful even on my slow-ish CI.

A better solution would use futures, but I'm not sure what futures are available to wait for process exit. Presumably, implementing those futures is assrt_cmd's job.

Note that I use a generic `CmdCond` enum which can describe a timeout condition but also "when that other command has exited" or "when that file matches a predicate".

You can steal code from https://gist.github.com/vincentdephily/592546c41ff9713adff234e5535aa6d4

**Comment by dylni** [comment]
@epage I created a crate that should help with this:
https://crates.io/crates/process_control

You can use [`Child::wait_for_output_with_timeout`](https://docs.rs/process_control/0.1.0/process_control/trait.Terminator.html#tymethod.wait_for_output_with_timeout) to completely run a process with a timeout.
