### ISSUE TITLE
Easy "stdout contains" assertions

### ISSUE THREAD

**Issue by killercup** [assert-rs/assert_cmd#11]
I'm trying to use this for a project instead of the published version of assert_cli. I'm super impressed by what you've accomplished here in the short time!

It seems that currently, there is no easy way to check that the output of a command contains some text. Or did I miss something?

Predicates only has a `str::contains` but `stdout` is a `Vec<u8>`. It seems that it could work with `predicate::function`, but it is quite cumbersome. I'm basically looking for good way of writing `.stdout(&predicate::function(|x: &Vec<u8>| String::from_utf8_lossy(x).contains("Done!")))` -- but ideally without the need to use `from_utf8_lossy`. This last requirement is also why I opened this issue here, and not on the predicates,  I expect we may need to talk about how to best deal with the `Vec<u8>` representation.

**Comment by epage** [comment]
Any `Predicate<str>` has an extension method `from_utf8` to turn it into one that should be usable for stdout... I hope. Can't remember if that has an explicit test. Check the `tests` folder for possible examples.

**Comment by killercup** [comment]
Ah, very cool. Couldn't find it because it's not yet in a released version. Sadly, it also doesn't seem to like `Vec<u8>` because "the trait `predicates::core::Predicate<std::vec::Vec<u8>>` is not implemented for `predicates::str::Utf8Predicate<predicates::str::ContainsPredicate>`".

**Comment by epage** [comment]
Didn't realize it wasn't published.  I'll get it out and update the tests, fixing ergonomics along the way.
