### ISSUE TITLE
Feature request: support for observable timing

### ISSUE THREAD

**Issue by detly** [assert-rs/assert_cmd#113]
I have a service-like application. It is started by some kind of service manager eg. systemd, procd, and interacts with the world in the following ways:

- mostly communicating via IPC (Cap'n Proto over ZeroMQ)
- to shut down requires `SIGTERM` or `SIGINT`
- calls system commands ie. spawns subprocesses

These parts are easy enough to test in integration tests — craft IPC messages, set up sockets, use a flag to echo commands and intercept them by capturing `stdout`. So I can test that eg. sending the IPC message `HELLO` results in command `true` being run (really, being echoed when testing).

But another important part of the observable behaviour of this program is the time between events. For example, if my program receives the IPC message `GOGOGO` it should reply with the IPC message `GOING` and then, four seconds later, run the command `gone`.

I currently don't have an easy way to test this aspect of the program though. It doesn't have to be super precise: by "four seconds" I generally mean 4±0.5s. So I could sleep for `duration - tolerance`, test for the negative, then sleep for `2 × tolerance` and test for the condition. But that's the kind of boilerplate it would be nice to have abstracted by a library.

So I have some questions:
- would you consider this in scope for assert_cmd?
- if so, is there a preferred way you'd want this implemented?

(I don't know if I'll have time to implement this, but knowing that info will help get me started if I do.)

**Comment by epage** [comment]
Generally, we've directed people elsewhere for more interactive testing, instead focusing on one-shot testing.  Maybe something like rexpect would work?

I'd definitely be interested in seeing what ends up working for you so we can look for synergy or so I can point people in a similar direction.

**Comment by detly** [comment]
Thanks for the information! I will let you know how I end up doing this, assuming it's not an extremely specific bespoke abomination.
