### ISSUE TITLE
[Feature Request] Report context when panic

### ISSUE THREAD

**Issue by qiujiangkun** [assert-rs/assert_cmd#114]
assert_cmd is very handy. However, I haven't found a way to print some infomation while panicking.
There is a `append_context()`, but it is not printed in assert failure.

I suggest we print context while panicking, like what `expect()` do vs `unwrap()`

**Comment by epage** [comment]
Could you clarify, are you referring to when the binary-under-test panics or when we call `panic` as part of our asserts?

Could you provide sample code of what happens today, what is missing, and what the code and output would look like in the future?

**Comment by qiujiangkun** [comment]
For example, I have an external tool called `check_device` that cheks the existence of the device. I hope the following program prints "Device does not exist" when `check_device`fails. Currently it just says assertion fails, without context that I could provide
```
use assert_cmd::assert::OutputAssertExt;
use assert_cmd::Command;

#[test]
fn test_device() {
    Command::new("check_device")
        .args(&["ens1"])
        .unwrap()
        .assert()
        .append_context("main", "Device does not exist due to blblbl")
        .success();
}
```

**Comment by epage** [comment]
To better understand where this is failing and why, could you provide the exact output, with `RUST_TRACEBACK=1`?

**Comment by epage** [comment]
(going back through old issues)

We had support for this but it looks like it was broken in #128

**Comment by epage** [comment]
nm, I misread it.  We still have this.  Going ahead and closing since we never got more cotnext as to whats missing.
