### ISSUE TITLE
Running in Tempdir, cleaning up generated files?

### ISSUE THREAD

**Issue by matthiasbeyer** [assert-rs/assert_cmd#126]
Hi,

is there a possibility to run my tested binary in a tempdir and also cleaning that up after a successful (or even after a failing) test?

My binary creates files, I would thus also need a way to check whether files where generated with the appropriate contents, and clean them up after the tests.

If there is no such feature, feel free to consider this a feature-request! :laughing:

**Comment by epage** [comment]
We've not baked in running in a tempdir but leave the file system operations to https://github.com/assert-rs/assert_fs, with the assumption people will most likely want to additional things, like setup some files before running the command or verify the files after.

For a simple example (though without `assert_cmd`), see https://github.com/sunng87/cargo-release/blob/b5db1c3c2686f2dcb91c2bf3f303b9f6e99f5945/src/cargo.rs#L236
