### ISSUE TITLE
Question regarding "flaky" commands

### ISSUE THREAD

**Issue by smoelius** [assert-rs/assert_cmd#127]
I have a command that succeeds most of the time, but fails with some small probability. I would like to run it at most N times and declare success once some run succeeds, or fail if all N runs fail. (Something like what [retry](https://github.com/jimmycuadra/retry) does.)

By "fail," I mean say that a predicate doesn't match a command's `stdout`.

I would like to check each run using `assert_cmd` (because it's awesome). However, given that failure means panic, I can't see an easy way to do this.

Do you have any suggestions on how to accomplish what I've described using `assert_cmd`?

**Comment by epage** [comment]
We could always add `try_` variants of the methods that return a status.

**Comment by smoelius** [comment]
So instead of writing:
```rust
Command::cargo_bin("foo")
    .unwrap()
    .assert()
    .success()
    .stdout(...);
```
I would write:
```rust
Command::cargo_bin("foo")
    .unwrap()
    .assert()
    .try_success()?
    .try_stdout(...)?;
```
Do I have the right idea?

**Comment by epage** [comment]
Yup!

**Comment by smoelius** [comment]
Is that an easy change, you think?

**Comment by epage** [comment]
The main issue is designing the error type.  After that, its relatively easy.  We could start with the error type not being too different than the panic message.

**Comment by smoelius** [comment]
Have I volunteered myself to submit a PR? :P

**Comment by epage** [comment]
Yes, yes you did ;)

**Comment by smoelius** [comment]
OK. Thanks. I'll try to get to work on this soon. :)
