### ISSUE TITLE
Running a binary in cargo workspace

### ISSUE THREAD

**Issue by jayvdb** [assert-rs/assert_cmd#164]
I am trying to run a binary in another package in the same cargo workspace, and it fails with

```
panicked at 'called `Result::unwrap()` on an `Err` value: CargoError { cause: Some(NotFoundError { path: "/path/to/workspace-root/target/debug/build/this-package-82904fc82eb19c14/binary-in-other-package" }) }', ...
```

**Comment by epage** [comment]
This is not supported.  You would need to work around this by compiling the binary, like with `escargot`.  So long as everything matches, this should be fast.  You can dig into https://github.com/clap-rs/clap/blob/master/tests/examples.rs to see how to make something like this work.

**Comment by jayvdb** [comment]
It could be supported, using something like https://crates.io/crates/cargo_metadata to find the binary, assuming it has been built. If you think it is out of scope, please close.

**Comment by epage** [comment]
> assuming it has been built

That is the key part to this.  `cargo_bin` works in integration tests because cargo guarantees that bins will be built before them.  Ensuring they are built is why I point people to `escargot`.
