### ISSUE TITLE
how to trigger binary builds from 'cargo test'

### ISSUE THREAD

**Issue by FrankReh** [assert-rs/assert_cmd#178]
This is not an issue with 'assert_cmd' per se. But maybe someone who uses it to get a binary path for a debug or release binary from their workspace has figured this out.

How to get 'cargo test' to trigger a build of the binaries (like a 'cargo build' would do), and how to get 'cargo test --release' to trigger the build of the release versions?

Is creating a shell script to call the build and test steps in series what folks have done?

**Comment by epage** [comment]
So long as your test is an integration test and in the same package as your binary, your binary will automatically be built for you.

For more exotic cases, you can look at `snapbox::compile_example` for how to get it done manually: https://docs.rs/snapbox/latest/src/snapbox/cmd.rs.html#1051-1080
