### ISSUE TITLE
Should `assert.output("text")` trim / normalize line endings?

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cmd#19]
Right now, `str` gets turned into a `Utf8<Difference>` set of predicates.  Should we add trimming and line ending normalization to that?

assert_cli did trimming.  This would allow people to work around it by directly passing in a predicate rather than relying on `IntoOutputPredicate`.

**Comment by mssun** [comment]
I don't think auto/explicitly trimming will help a lot. I think the current behavior is very intuitive. I expect this API will compare the output exactly byte by byte.

**Comment by zetok** [comment]
Rather than breaking current intuitive behaviour of the function, why not add another function for the functionality, something like `output_trimmed` or `output_fuzzy`?

**Comment by epage** [comment]
The reason this question even came up is that trimming was the default behavior of `assert_cli` and as of right now `assert_cmd` does not mirror that.  

> Rather than breaking current intuitive behaviour of the function, why not add another function for the functionality, something like `output_trimmed` or `output_fuzzy`?

Unlike `assert_cli`, I'm trying to not add a lot of variants of the assert functions but instead rely on users creating custom predicates.  We happen to be providing shortcuts for some common cases instead of requiring the full predicate to be spelled out.

**Comment by epage** [comment]
Going to go ahead and say "no" due to principle of least surprise
