### ISSUE TITLE
Does not work in GitHub Actions

### ISSUE THREAD

**Issue by webern** [assert-rs/assert_cmd#205]
I have a problem that I do not understand. In my GitHub actions runs, assert_cmd fails to fine the binary.

` CargoError { cause: Some(NotFoundError { path: "/home/runner/work/twoliter/twoliter/target/debug/twoliter" }) }`

This is working locally. It is a workspace where the tests are being called from the root of the Cargo workspace with `cargo test`.

**Comment by epage** [comment]
Were you using something like [`Command::cargo_bin`](https://docs.rs/assert_cmd/latest/assert_cmd/cmd/struct.Command.html#method.cargo_bin) inside of a unit test?

Be sure to review the limitations: https://docs.rs/assert_cmd/latest/assert_cmd/cargo/index.html#limitations

**Comment by webern** [comment]
Oh, I think the issue is perhaps because it was in a "unit" test instead of in the `tests` directory. I think what I was doing was unsupported. I'm going to use the clap structs directly instead. Thank you.
