### ISSUE TITLE
How to use together with proptest?

### ISSUE THREAD

**Issue by MaxG87** [assert-rs/assert_cmd#215]
For a CLI tool I try to develop I want to combine `assert_cmd` and [`proptest`](https://proptest-rs.github.io/). I want to test the main features of the program through its CLI. However, I also want to generate certain inputs to cover more than the usual examples one would write.

So far, I just use `cmd.assert().success()`, which works fine for passing tests. However, for failing tests I see the error message of every failing example. For normal test assertions, there is the `prop_assert!` macro which replaces `assert!` and only prints relevant outputs. However, I couldn't figure out how to use it together with `cmd.assert()`.

I am relatively new to Rust so please bear with me in case I missed something obvious.

Could you please advice how to best combine `prop_assert!` with `assert_cmd`?

**Comment by epage** [comment]
They key phrase on [prop_assert!`](https://docs.rs/proptest/latest/proptest/macro.prop_assert.html)s docs is

> Similar to assert! from std, but returns a test failure instead of panicking if the condition fails.

We offer `try_` variants of our assertions (e.g. [`try_success`](https://docs.rs/assert_cmd/latest/assert_cmd/assert/struct.Assert.html#method.try_success) that report a status.  You could make a function to convert the error type using `https://docs.rs/proptest/latest/proptest/test_runner/enum.TestCaseError.html#method.fail` and do `.map_err(cmd_to_proptest)?`

**Comment by MaxG87** [comment]
Thank you very much!

I rewrote `cmd.assert().success().stdout("Hello, world!\n");` to `cmd.assert().try_success()?.try_stdout("Hello, world!\n")?;`. With that I get error messages only for the last, most reduced, test failure.
