### ISSUE TITLE
`with_stdin` will take the ownership of command

### ISSUE THREAD

**Issue by mssun** [assert-rs/assert_cmd#22]
The `with_stdin` will take the ownership of command. Therefore you cannot write chained functions like this:

```
Command::new("cat")
    .arg("-A")
    .with_stdin("42")
    .assert()
    .success();
```

Error:
```
error[E0507]: cannot move out of borrowed content
  --> /xxx.rs:43:5
   |
43 | /     Command::new("cat")
44 | |         .arg("-A")
   | |__________________^ cannot move out of borrowed content
```

**Comment by epage** [comment]
Since `spawn` takes in a `&mut`, I could probably loosen this requirement to `&mut`.

**Comment by mssun** [comment]
Good, thanks.

I'm trying to use `assert-cmd` for our integration tests: https://github.com/mesalock-linux/mesabox/pull/24.

It will be very helpful if this issue can be quickly fixed. Thank you for the amazing project.

**Comment by epage** [comment]
Since this was a breaking change, I'm publishing it as v0.5.0 right now.

Did you test your conversion with #23?  Should have probably checked with that first in case you find more issues :)

**Comment by mssun** [comment]
It works fine for my current usage.

The only concern is that `with_stdin` have to be the last function before `assert` since it returns `StdInCommand` instead of `Command`.

**Comment by epage** [comment]
Yup, didn't have an  idea for a better way of doing that.

**Comment by mssun** [comment]
Thanks anyway. I probably will come up some other features or bugs later during my refactoring :)
