### ISSUE TITLE
Spawn a process

### ISSUE THREAD

**Issue by ghenry** [assert-rs/assert_cmd#227]
Hi all,

Pretty new to integration tests with Rust and following the examples in the [Command-Line Rust book](https://www.oreilly.com/library/view/command-line-rust/9781098109424/). My test flow is like so, but I'd like `sentrypeer` to run in the background. What can `assert_cmd` help with there or should I move running `sentrypeer` into a `setup()` style like the main [Rust book talks about](https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests)?

I was hoping `.spawn()` would do it, but that's only available in `std::process::Command`. Thanks for reading!

```rust
use assert_cmd::Command;
use predicates::prelude::*;

#[test]
#[ignore = "not yet implemented"]
fn tls_probe() {
    // Delete our JSON log file
    let mut json_log = Command::new("rm");
    json_log.arg("../sentrypeer_json.log");

    // Start sentrypeer in the background
    let mut cmd = Command::new("../sentrypeer");
    // Enable debug mode, responsive SIP mode, and JSON logging using the default JSON
    // log file
    cmd.arg("-drj");

    // Debug mode will show the transport type which is TLS
    cmd.assert()
        .success()
        .stdout(predicate::str::contains("TLS"));

    // Run our SIP tester
    let mut sipexer_cmd = Command::new("../tests/tools/sipexer");
    sipexer_cmd.arg("-tls-insecure").arg("tls:127.0.0.1:5061");
    sipexer_cmd.assert().success();

    // Check that the JSON log file has been created
    let mut json_log = Command::new("cat");
    json_log.arg("../sentrypeer_json.log");
    json_log
        .assert()
        .success()
        .stdout(predicate::str::contains("TLS"));
}
```

**Comment by epage** [comment]
This library is specifically designed for one-shot running of programs. For the long-running program, you can manually process things, combine assertions together from the `snapbox` library, or use `rexpect`.

**Comment by ghenry** [comment]
Thanks @epage I've re-worked this using `spawn()` now. Thanks for the reply.
