### ISSUE TITLE
Feature request: fixture file as input to pipe (`with_stdin`)

### ISSUE THREAD

**Issue by mssun** [assert-rs/assert_cmd#24]
It will be very useful if I can use a fixture file as input

**Comment by epage** [comment]
Thats a really great idea!

For stdin, its just a matter of coming up with the name.

For stdout, stderr, the challenge is we won't know if its intended to be binary or `str` (this matters for the new feature I'm writing). I wonder if its best to l leave it as `stdout(predicte::path::eq_file(path))`

**Comment by epage** [comment]
Also, something else for us to consider with `stdin` is we might want to support chunking in case someone is testing a really large file.

**Comment by mssun** [comment]
Thanks @epage, I didn't notice the usage of `stdout(predicte::path::eq_file(path))` actually. I think it's OK for me to use predicates.

In terms of the name, how about `with_fixture_stdin`?

**Comment by epage** [comment]
> Thanks @epage, I didn't notice the usage of stdout(predicte::path::eq_file(path)) actually. I think it's OK for me to use predicates.

I've gone ahead and removed stdout/stderr from this to make our narrowed focus clear.

> In terms of the name, how about with_fixture_stdin?

imo whether you use a file or in-memory string, both would be considered fixtures, right?

So one option is `with_stdin_file`?  Another options is `with_stdin().from_bytes("Hello World")` / `with_stdin().from_path("./hello.txt")`.

**Comment by mssun** [comment]
> I've gone ahead and removed stdout/stderr from this to make our narrowed focus clear.

Yes, you are right.

I think `with_stdin().from_bytes("Hello World") / with_stdin().from_path("./hello.txt")` are more readable.

**Comment by epage** [comment]
Publishing v0.6.0 with this fix.  Sorry for the delay.

**Comment by mssun** [comment]
I guess I cannot use `.stdout(predicate::path::eq_file(Path::new("filename"))` right now?

I'm a little confused about `FileContentPredicate`, `BinaryFilePredicate`, and `StrFilePredicate`. Anyway, can you give me an example of how to compare content in a fixture file with the stdout (in binary or in str). Thank you so much!

**Comment by epage** [comment]
Yeah, I realized that on closer inspection and opened https://github.com/assert-rs/predicates-rs/issues/56

My plan has been to finish https://github.com/assert-rs/predicates-rs/issues/7 first because I've started it and it is more invasive but it is larger and controversial, so it might take longer to get in.

**Comment by mssun** [comment]
I see. Thank you @epage. Can you ping me if it's ready to use?

**Comment by epage** [comment]
Just to check, is that another blocking issue for you?

> I see. Thank you @epage. Can you ping me if it's ready to use?

Alternatively, you could subscribe to the issue?

**Comment by mssun** [comment]
Yes, my expectation is to pipe in fixture files and compare stdout with fixture files. I have subscribed these issues you mentioned. Thanks.
