### ISSUE TITLE
Feature request: providing `stdout_only` or `stderr_only` APIs

### ISSUE THREAD

**Issue by mssun** [assert-rs/assert_cmd#25]
For example, I want to assert a command which only have specific stdout but does not have any stderr message. Currently, I have to write `.stdout("msg").stderr("")` or `stdout("").stderr("error msg")`.

**Comment by mssun** [comment]
I'm debating on this suggestion myself. Besides these two, how about no output? Not sure if it's OK for current simplicity.

**Comment by epage** [comment]
This feels very specific to me which makes me lean to not adding these.

One reason why it feels very specific is generally a test should verify one requirement and I suspect there are few applications where you have to have only one or neither to check most requirements.

**Comment by epage** [comment]
Feel free to continue the conversation to help me better understand why this would be important, but for now I'm closing this.
