### ISSUE TITLE
Distinction between `Assert::set_stdin()` and `with_stdin` is confusing

### ISSUE THREAD

**Issue by zetok** [assert-rs/assert_cmd#29]
No idea if it doesn't actually work, or if I'm doing something wrong and API is simply allowing for it, but either way it should be fixed.

`assert_cmd = "0.6"`

my test case:

```rust
#[test]
fn broek_dep() {
    Command::new("cat")
        .assert()
        .set_stdin(vec![0])
        .stdout("\0")
        .success();
}
```

Which results in:

```
thread 'broek_dep' panicked at 'Unexpected stdout
command=`"cat"`
stdin=``````
code=0
stdout=``````
stderr=``````
',
```

---

Also on a side note, output of `assert_cmd` when there's an error is rather confusing and not helpful when you're trying to deal with input/output that consists of raw, often unprintable, bytes. `Debug` output without additional ``` would work a lot better IMO.

**Comment by zetok** [comment]
>Are you converting over from `assert_cli`?

No, but I've found out about `assert_cli` first from a blog post, and then I've looked at docs of both crates to see what's different.

>  Any ideas for better names or other means to help people use the right function and avoid the one more so meant for internal purposes (but is `pub` for anyone writing custom logic)

I think that having something like a bold **Warning** in the documentation of the function explaining that this might not be what they want and recommending using `with_stdin` instead would do the trick.

**Comment by epage** [comment]
Forgot to reply to:

> Also on a side note, output of assert_cmd when there's an error is rather confusing and not helpful when you're trying to deal with input/output that consists of raw, often unprintable, bytes. Debug output without additional ``` would work a lot better IMO.

Please open a distinct issue for this

**Comment by epage** [comment]
> I think that having something like a bold Warning in the documentation of the function explaining that this might not be what they want and recommending using with_stdin instead would do the trick.

Documentation just patches over problems and only helps so far as it is read (e.g. the current documentation already pretty clearly states how the parameter to `set_stdin` works).

I'm considering things like
- Changing the name (adding "context")
- Making this functions `pub(crate)` until there is a need and handle it then
- Try to make clearer the idea that the problem has already run by the time `Assert` exists.
