### ISSUE TITLE
Documentation for migrating from assert_cli

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cmd#30]
Things to cover
- Command is run at `assert` or earlier and not at the end of the expression
- Output predicates don't automatically trim (unless we change it, see https://github.com/assert-rs/assert_cmd/issues/19)
- `success` is not automatically asserted.

**Comment by luser** [comment]
I just did this manually and the biggest thing it took me a while to figure out was that I should be using `std::process::Command`, and that this crate adds additional methods via extension traits. I could also have used some more detailed documentation on how the stdout/stderr predicates work. (Even just mentioning that the argument can be a predicate and linking to the `predicates` crate docs would have helped!)
