### ISSUE TITLE
Allow CommandCargoExt to pass build arguments

### ISSUE THREAD

**Issue by quininer** [assert-rs/assert_cmd#34]
Sometimes we want to provide testing for different features bin.

**Comment by epage** [comment]
Sorry I haven't responded earlier.

Is the primary concern features?

Some of the challenges
- Right now, we directly return a `Command`.  Adding more to this API makes it so we can't.  How should we bridge that gap?
- What is in scope and what isn't?
- The API for the `main_binary_path`s

**Comment by epage** [comment]
I've started mapping out what we might due to the API to help

Please check out https://github.com/assert-rs/assert_cmd/issues/44 and provide feedback

**Comment by epage** [comment]
The recommendation is to call into `escargot` directly.  You can find an example within `assert_cmd`: https://github.com/assert-rs/assert_cmd/blob/master/src/cargo.rs#L137
