### ISSUE TITLE
What's the easiest way to create predicates that match patterns?

### ISSUE THREAD

**Issue by gnzlbg** [assert-rs/assert_cmd#48]
For example, I need to match:

```
lib_crate::sum_array (src/lib.rs:6):
 push    rbp
 mov     rbp, rsp
 test    rsi, rsi
  je      LBB13_1
  lea     r9, [4*rsi, -, 4]
 shr     r9, 2
 inc     r9
 cmp     r9, 8
 jae     LBB13_4
  xor     eax, eax
 mov     rcx, rdi
 jmp     LBB13_13
LBB13_1:
 xor     eax, eax
 pop     rbp
 ret
```

on macos, but on windows all the LBB13_... are LBB14_.. and they change on linux as well. Also on windows and linux, the push+mov at the beginning, and pop at the end parts of my pattern are not present. 

In rustc, I would write something like this

```
lib_crate::sum_array (src/lib.rs:6):
{{.*}}
 test    rsi, rsi
 je      LBB{{.*}}_1
 lea     r9, [4*rsi, -, 4]
 shr     r9, 2
 inc     r9
 cmp     r9, 8
 jae     LBB{{.*}}_4
 xor     eax, eax
 mov     rcx, rdi
 jmp     LBB{{.*}}_13
LBB{{.*}}_1:
 xor     eax, eax
{{.*}}
 ret
```

where the `{{regexp}}` is used to match any pattern.

What's the easiest way of doing something like this to assert outputs that using `assert_cmd` ?

**Comment by epage** [comment]
If you dig into the [`predicates` prelude](https://docs.rs/predicates/0.9.0/predicates/prelude/predicate/str/index.html), you'll see a `predicate::str::is_match` that allows regex-based matches.

```rust
extern crate assert_cmd;
extern crate predicates;

use std::process::Command;

use assert_cmd::prelude::*;
use predicates::prelude::*;

#[test]
fn code_example() {
    Command::main_binary()
        .unwrap()
        .env("exit", "42")
        .assert()
        .stdout(predicate:str::is_match("<pattern>"));
}
```

**Comment by casey** [comment]
I wound up finding this issue when I was trying to figure out how to use regexes, and the above example has a couple of typos. Just in case it helps anyone else, here is the corrected example:

```rust
#[test]
fn code_example() {
    Command::main_binary()
        .unwrap()
        .env("exit", "42")
        .assert()
        .stdout(predicate::str::is_match("<pattern>").unwrap());
}
```
