### ISSUE TITLE
How to compare stdout with a Vec<u8>?

### ISSUE THREAD

**Issue by mssun** [assert-rs/assert_cmd#50]
I want compare command stdout with my tested app's stdout like this:

```
    let output = Command::new("uname").output().unwrap();
    let stdout = output.stdout;
    new_cmd!()
        .assert()
        .success()
        .stdout(stdout)    // this will give an error
        .stderr("");
```

I can't find a simple API from predicates. Can you suggest a proper way to handle this?

**Comment by epage** [comment]
So if we go to the docs, `.stdout()` takes a [`IntoOutputPredicate`](https://docs.rs/assert_cmd/0.9.1/assert_cmd/assert/trait.IntoOutputPredicate.html).  There is an implementation that takes a `&'static [u8]`.  

A `Vec<u8>` can be derefed as a `&[u8]` but the lifetime is a problem (possibly a bug?).

But you can use it for [inspiration](https://docs.rs/assert_cmd/0.9.1/src/assert_cmd/assert.rs.html#492).

So in theory, you could do something like
```rust
use predicates::prelude::*;

    let output = Command::new("uname").output().unwrap();
    let stdout = output.stdout;
    new_cmd!()
        .assert()
        .success()
        .stdout(predicate::eq(&stdout as &[u8]))
        .stderr("");
```

**Comment by epage** [comment]
And I created https://github.com/assert-rs/assert_cmd/issues/51
