### ISSUE TITLE
Support for features

### ISSUE THREAD

**Issue by dbrgn** [assert-rs/assert_cmd#59]
Hi. I'm currently a user of `assert_cli` in [tealdeer](https://github.com/dbrgn/tealdeer/) and am thinking about moving to `assert_cmd`. The main issue I'm facing there is that the binary (when calling `Assert::main_binary()`) is always compiled with default features, even if I compile the tests with `--no-default-features`.

Does `assert_cmd` have a solution for this? Ideally I'd either be able to pass the features to the `main_binary` or `cargo_bin` methods, or would have a way to specify the features per-invocation by other means (e.g. `set_features(&["networking"])` or `set_features(&[])`). This way, I could test different feature flags from a single test binary.

Alternatively compiling the main binary with the same flags as the test binary would be fine too.

**Comment by epage** [comment]
Unfortunately, there is not a good way to auto-detect features and I'm wanting to be cautious about effectively embedding a cargo API into `assert_cmd`.

The good news is you can instead call into the API that `assert_cmd` is built on top of.  We even include [an example in the docs](https://docs.rs/assert_cmd/0.10.1/assert_cmd/cargo/index.html)

We need to expand the docs to list caveats of the simple API.  We should be sure to list features in that.

**Comment by epage** [comment]
Now documented as of #62

**Comment by dbrgn** [comment]
Thanks!

**Comment by epage** [comment]
So it looks like we can [programmatically get featutes](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts)

The downsides
- Only works from `build.rs`.  We'd have to write a code-generator, have clients call the code-generator, and then include the generated code.  Not very ergonomic
- It changes the name in an irreversible way.
