### ISSUE TITLE
`main_binary` takes ~300ms per invocation

### ISSUE THREAD

**Issue by epage** [assert-rs/assert_cmd#6]
From @rcoh https://github.com/assert-rs/assert_cli/issues/100

- `assert_cli` version: 0.5
- Rust version: 1.25.0
- OS and version: Ubuntu 16.04
Unfortunately, `cargo run` takes at minimum about 300ms on my computer:
```
➜  angle-grinder git:(master) ✗ time cargo run --bin agrind -- '* | json | count' --file test_files/empty
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/agrind '* | json | count' --file test_files/empty`
No data
cargo run --bin agrind -- '* | json | count' --file test_files/empty  0.22s user 0.06s system 92% cpu 0.307 total
```

It makes it impractical to run hundreds of integration tests with assert_cli.

I'm not positive what a better way would be -- I guess running the binary in dist directly if it exists?

### Workaround

See [assert_cmd::cargo's docs](https://docs.rs/assert_cmd/0.10.1/assert_cmd/cargo/index.html)

**Comment by epage** [comment]
From killercup cargo issue: https://github.com/rust-lang/cargo/issues/5315

**Comment by epage** [comment]
So a user can work around this in assert_cmd by accessing `cargo_bin_path`, etc.  This causes the 300ms to only be hit once instead of on every run.

Should we provide an API on to simplify this?

Example
```rust
lazy_static!{
   const BIN_FIXTURE = assert_cmd::cargo_bin("bin_fixture");
}
...
println!("{:?}", BIN_FIXTURE.path());
BIN_FIXTURE.cmd().arg("stdout", 42).unwrap();
```

**Comment by zetok** [comment]
Additions to API aren't needed, but docs that would point out this functionality would be really helpful. Since right now one needs to go to the issue tracker of the crate to find the solution, which is suboptimal.

As for why an additional API is not needed – e.g. `regex` crate doesn't have an additional API for creating a static regexp, but it has a great documentation where it shows on the "main" page of its docs an example on how to use `lazy_static` to reduce unnecessary computations. [It's nice.](https://docs.rs/regex/1.0.2/regex/#example-avoid-compiling-the-same-regex-in-a-loop)


Also, a working example, freshly ~copypasted from a test for anyone else who's interested:

```rust
use std::path::PathBuf;

lazy_static! {
    static ref BIN_PATH: PathBuf = assert_cmd::cargo::main_binary_path().unwrap();
}

#[test]
fn test_bin() {
    Command::new(&*BIN_PATH).assert().success();
}
```

**Comment by epage** [comment]
> As for why an additional API is not needed – e.g. regex crate doesn't have an additional API for creating a static regexp

The difference is the main purpose of this crate is running programs.  Its a bit of a wart in the API to have functions that provide paths to programs you could run.  It'd be nice if `Command` supported `clone`.

**Comment by epage** [comment]
I think at this point this is mostly kept open to track and be aware of the slow down.  We have workarounds but thats all they are.

**Comment by killercup** [comment]
Have we ever measured this again with newer cargo versions? I recall them
adding some caching for this, too.

**Comment by rcoh** [comment]
FYI, I just reran the original example that started everything. On the same laptop with nightly, it takes 125ms, so twice as fast as before. A big enough change that it actually feels way faster :+1: 
```
cargo 1.31.0-nightly (ad6e5c003 2018-09-28)
```

**Comment by epage** [comment]
Good idea.  I should add a benchmark that compares running the underlying program against running it via cargo.

**Comment by epage** [comment]
More data
- My computer
- `cargo 1.31.0-nightly (de314a8b2 2018-09-21)`
- Running #56 

`test escargot_rebuild ... bench: 368,686,700 ns/iter (+/- 64,925,719)`

**Comment by sharkdp** [comment]
I think we might have run into a related issue [in `bat`](https://github.com/sharkdp/bat/issues/394). I tried to implement the workaround but couldn't quite figure it out as some of the referenced functions are not available anymore(?). Is there still a workaround for this?

**Comment by epage** [comment]
@sharkdp sorry, I have been maintaining [the work around in the docs](https://docs.rs/assert_cmd/0.10.1/assert_cmd/cargo/index.html) but forgot to update this issue.  I've done so now.

**Comment by sharkdp** [comment]
@epage Thank you very much! Sorry for not checking the documentation.

If I understand this correctly, this will still potentially compile (part of) the project in the first unit test, right?

(link to my current implementation: https://github.com/sharkdp/bat/pull/398)

**Comment by epage** [comment]
> If I understand this correctly, this will still potentially compile (part of) the project in the first unit test, right?

To get the path, it will still need to call into `cargo`.  Whether anything builds is a different question.  If you match target/release with what you are building, then it should reuse what was built before.

I recommend passing in `current_release`.  An unfortunate thing is if you pass in `current_target` and you did not pass `--target` into `cargo test`, then it will rebuild everything on first test.  There was no good answer between correctness and performance, so the default for `Command::main_bin` and the workaround in the docs is `current_target`

**Comment by sharkdp** [comment]
@epage Thank you very much for the explanation.

**Comment by sourcefrog** [comment]
On Windows, for my program `conserve`, switching to assert_cmd from my own hacky code seems to have increased the overall test time from ~3:00 to ~4:00.

https://ci.appveyor.com/project/sourcefrog/conserve/builds/20036005

I think it'd at least be nice if this was more prominent in the docs homepage.

**Comment by epage** [comment]
@sourcefrog looking at your log, it looks like you are more so having problems with #57 (realized I should create a dedicated issue rather than pointing people to #4).

#57 does need to be mentioned in the docs but I'm unsure if the top-level docs are appropriate for each workaround or special case.  I also noticed that this issue's workaround is only mentioned in the `cargo` module and not on the trait or functions.  If someone jumps straight to one of those, they need to be aware of these workarounds.

I've created https://github.com/assert-rs/assert_cmd/issues/58 to document the workaround and try to find a way to improve visibility.
