### ISSUE TITLE
Possible bug `with_stdin`

### ISSUE THREAD

**Issue by coreyja** [assert-rs/assert_cmd#71]
I'm running into what I think is a bug with `with_stdin`, but I also could be misunderstanding the use-case for it!

I have boiled down my usage, to something where I can reproduce with just `cat`

```
let mut cmd = Command::new("cat");
cmd
    .with_stdin()
    .buffer("42");
let assert = cmd.assert();
assert
  .success()
  .stdout("42");
```

I expected this to function kinda like `echo 42 | cat` which outputs `42`

However this assert is not passing for me. Am I misunderstanding something, or is this a bug? I am using version `0.11.0` right now

Thanks for the time, and for writing and maintaining this library!

**Comment by epage** [comment]
I think this is more of a bug in the documentation than in stdin handling.  #72 updates the examples to be
```rust
/// ```rust
/// use assert_cmd::prelude::*;
///
/// use std::process::Command;
///
/// let mut cmd = Command::new("cat");
/// cmd
///     .arg("-et");
/// cmd
///     .with_stdin()
///     .buffer("42")
///     .assert()
///     .stdout("42");
/// ```
```

I will say, this is very unergonomic but I'm at a loss on how to improve it.

**Comment by coreyja** [comment]
Awesome! I will try this out in my project soon with the updated documentation and report back if I run into any issues!

Thanks so much for the quick response!
