### ISSUE TITLE
Renaming a crate

### ISSUE THREAD

**Issue by juanibiapina** [assert-rs/assert_cmd#90]
Steps to reproduce:

- write an integration test that uses the main binary like this: `...Command::cargo_bin("cli-name").unwrap()`
- run the tests
- rename the crate in `Cargo.yaml` (thus renaming the binary)
- break some code
- run the tests again

The tests pass! One easy solution is to use `env!(CARGO_PKG_NAME)`, but I'm more concerned about it having used a stale cache without even noticing it was doing the "wrong thing".

I can see how this happens and that this crate is not doing anything wrong, but I just wanted to point this out.

**Comment by epage** [comment]
Yeah, can't think of anything we should do for this but at least we now have a searchable problem / solution.  Thanks!
