### ISSUE TITLE
src/cargo.rs test fails to compile

### ISSUE THREAD

**Issue by ignatenkobrain** [assert-rs/assert_cmd#95]
```rust
---- src/cargo.rs - cargo (line 29) stdout ----
error[E0463]: can't find crate for `serde_derive` which `escargot` depends on
 --> src/cargo.rs:31:5
  |
5 | use escargot;
  |     ^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
Couldn't compile the test.

failures:
    src/cargo.rs - cargo (line 29)
```

I run simple `cargo test` and it fails here. Any ideas what might be wrong?

**Comment by epage** [comment]
What version of rustc are you using?

In the CI and on my machine (both using 1.42), it compiles without a problem.

See https://dev.azure.com/assert-rs/assert-rs/_build/results?buildId=103&view=logs&j=7a9815c9-11be-5f71-bdb7-7117ff358526&t=9db795f0-d5b8-5729-e1e6-773c1d9c7b95

**Comment by decathorpe** [comment]
I have continued OP's work and cannot reproduce the original issue with assert_cmd 1.0.2. Feel free to close.
